FROM java:8-jdk-alpine

ENV PYTHON_VERSION 3.5.2-r2

# Install given python version
RUN apk update \
 && apk add python3=$PYTHON_VERSION \
 && apk add python3-dev=$PYTHON_VERSION

# Upgrade pip
RUN pip3 install --upgrade pip

# General dependencies
RUN apk update && \
    apk add curl bash

ENV SPARK_VERSION 2.2.1
ENV SPARK_PACKAGE spark-$SPARK_VERSION-bin-hadoop2.7
ENV SPARK_HOME /usr/spark-$SPARK_VERSION
ENV PATH $PATH:$SPARK_HOME/bin
RUN curl -sL --retry 3 \
    "http://archive.apache.org/dist/spark/spark-$SPARK_VERSION/$SPARK_PACKAGE.tgz" \
    | gunzip \
    | tar x -C /usr/ \
 && mv /usr/$SPARK_PACKAGE $SPARK_HOME \
 && rm -rf $SPARK_HOME/examples

ENV PYSPARK_PYTHON python3
ENV PYTHONPATH $SPARK_HOME/python
